### ISSUE TITLE
[Bug] Error when using docker-compose

### ISSUE THREAD

**Issue by matthewdias** [matthewdias/kitsu-plex-scrobbler#9]
For some reason, using the same options works in `docker run`, but throws this error in `docker-compose`.

Docker for Mac:

```
  kitsu-plex-scrobbler:
    image: matthewdias/kitsu-plex-scrobbler
    privileged: true
    restart: always
    network_mode: host
    environment:
      - KITSU_CLIENT=dd031b32d2f56c990b1425efe6c42ad847e7fe3ab46bf1299f05ecd856bdb7dd
      - KITSU_SECRET=54d7307928f63414defd96399fc31ba847961ceaecef3a5fd93144e960c0e151
      - KITSU_USERNAME=<username>
      - KITSU_PASSWORD=<password>
      - PLEX_HOST=http://host.docker.internal:32400
      - PLEX_TOKEN=<token>
      - PLEX_LOG="/logs/Plex Media Server.log"
      - PLEX_LIBRARIES=Anime
    volumes:
      - "/Users/Matthew/Library/Logs/Plex Media Server:/logs"
```

```
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (watch for "/logs/Plex Media Server.log" failed: undefined)
    at Tail.emit (events.js:171:17)
    at Tail.watch (/app/node_modules/tail/lib/tail.js:100:12)
    at new Tail (/app/node_modules/tail/lib/tail.js:84:10)
    at Object.<anonymous> (/app/src/index.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitsu-plex-scrobbler@0.0.1 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kitsu-plex-scrobbler@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-10T04_29_03_550Z-debug.log
ERROR: "start" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitsu-plex-scrobbler@0.0.1 start-docker: `run-p start inotify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kitsu-plex-scrobbler@0.0.1 start-docker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-10T04_29_03_869Z-debug.log
```
